#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Gestion_Etudiants.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Gestion_Etudiant")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertetudiant(etudiant instance);
    partial void Updateetudiant(etudiant instance);
    partial void Deleteetudiant(etudiant instance);
    partial void Insertfiliere(filiere instance);
    partial void Updatefiliere(filiere instance);
    partial void Deletefiliere(filiere instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WPF_Gestion_Etudiants.Properties.Settings.Default.Gestion_EtudiantConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<etudiant> etudiants
		{
			get
			{
				return this.GetTable<etudiant>();
			}
		}
		
		public System.Data.Linq.Table<filiere> filieres
		{
			get
			{
				return this.GetTable<filiere>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.etudiants")]
	public partial class etudiant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CNE;
		
		private string _Nom;
		
		private string _Prenom;
		
		private string _email;
		
		private string _Sexe;
		
		private System.Nullable<System.DateTime> _DateNaissance;
		
		private string _Addresse;
		
		private string _Phone;
		
		private System.Nullable<int> _FiliereId;
		
		private EntityRef<filiere> _filiere;
		
		private EntityRef<filiere> _filiere1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCNEChanging(string value);
    partial void OnCNEChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnPrenomChanging(string value);
    partial void OnPrenomChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnSexeChanging(string value);
    partial void OnSexeChanged();
    partial void OnDateNaissanceChanging(System.Nullable<System.DateTime> value);
    partial void OnDateNaissanceChanged();
    partial void OnAddresseChanging(string value);
    partial void OnAddresseChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnFiliereIdChanging(System.Nullable<int> value);
    partial void OnFiliereIdChanged();
    #endregion
		
		public etudiant()
		{
			this._filiere = default(EntityRef<filiere>);
			this._filiere1 = default(EntityRef<filiere>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CNE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CNE
		{
			get
			{
				return this._CNE;
			}
			set
			{
				if ((this._CNE != value))
				{
					this.OnCNEChanging(value);
					this.SendPropertyChanging();
					this._CNE = value;
					this.SendPropertyChanged("CNE");
					this.OnCNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(50)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prenom", DbType="VarChar(50)")]
		public string Prenom
		{
			get
			{
				return this._Prenom;
			}
			set
			{
				if ((this._Prenom != value))
				{
					this.OnPrenomChanging(value);
					this.SendPropertyChanging();
					this._Prenom = value;
					this.SendPropertyChanged("Prenom");
					this.OnPrenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexe", DbType="VarChar(10)")]
		public string Sexe
		{
			get
			{
				return this._Sexe;
			}
			set
			{
				if ((this._Sexe != value))
				{
					this.OnSexeChanging(value);
					this.SendPropertyChanging();
					this._Sexe = value;
					this.SendPropertyChanged("Sexe");
					this.OnSexeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateNaissance", DbType="Date")]
		public System.Nullable<System.DateTime> DateNaissance
		{
			get
			{
				return this._DateNaissance;
			}
			set
			{
				if ((this._DateNaissance != value))
				{
					this.OnDateNaissanceChanging(value);
					this.SendPropertyChanging();
					this._DateNaissance = value;
					this.SendPropertyChanged("DateNaissance");
					this.OnDateNaissanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Addresse", DbType="VarChar(100)")]
		public string Addresse
		{
			get
			{
				return this._Addresse;
			}
			set
			{
				if ((this._Addresse != value))
				{
					this.OnAddresseChanging(value);
					this.SendPropertyChanging();
					this._Addresse = value;
					this.SendPropertyChanged("Addresse");
					this.OnAddresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiliereId", DbType="Int")]
		public System.Nullable<int> FiliereId
		{
			get
			{
				return this._FiliereId;
			}
			set
			{
				if ((this._FiliereId != value))
				{
					if ((this._filiere.HasLoadedOrAssignedValue || this._filiere1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFiliereIdChanging(value);
					this.SendPropertyChanging();
					this._FiliereId = value;
					this.SendPropertyChanged("FiliereId");
					this.OnFiliereIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filiere_etudiant", Storage="_filiere", ThisKey="FiliereId", OtherKey="filiereId", IsForeignKey=true)]
		public filiere filiere
		{
			get
			{
				return this._filiere.Entity;
			}
			set
			{
				filiere previousValue = this._filiere.Entity;
				if (((previousValue != value) 
							|| (this._filiere.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._filiere.Entity = null;
						previousValue.etudiants.Remove(this);
					}
					this._filiere.Entity = value;
					if ((value != null))
					{
						value.etudiants.Add(this);
						this._FiliereId = value.filiereId;
					}
					else
					{
						this._FiliereId = default(Nullable<int>);
					}
					this.SendPropertyChanged("filiere");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filiere_etudiant1", Storage="_filiere1", ThisKey="FiliereId", OtherKey="filiereId", IsForeignKey=true, DeleteRule="CASCADE")]
		public filiere filiere1
		{
			get
			{
				return this._filiere1.Entity;
			}
			set
			{
				filiere previousValue = this._filiere1.Entity;
				if (((previousValue != value) 
							|| (this._filiere1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._filiere1.Entity = null;
						previousValue.etudiants1.Remove(this);
					}
					this._filiere1.Entity = value;
					if ((value != null))
					{
						value.etudiants1.Add(this);
						this._FiliereId = value.filiereId;
					}
					else
					{
						this._FiliereId = default(Nullable<int>);
					}
					this.SendPropertyChanged("filiere1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.filieres")]
	public partial class filiere : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _filiereId;
		
		private string _Nom;
		
		private string _responsable;
		
		private EntitySet<etudiant> _etudiants;
		
		private EntitySet<etudiant> _etudiants1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfiliereIdChanging(int value);
    partial void OnfiliereIdChanged();
    partial void OnNomChanging(string value);
    partial void OnNomChanged();
    partial void OnresponsableChanging(string value);
    partial void OnresponsableChanged();
    #endregion
		
		public filiere()
		{
			this._etudiants = new EntitySet<etudiant>(new Action<etudiant>(this.attach_etudiants), new Action<etudiant>(this.detach_etudiants));
			this._etudiants1 = new EntitySet<etudiant>(new Action<etudiant>(this.attach_etudiants1), new Action<etudiant>(this.detach_etudiants1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_filiereId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int filiereId
		{
			get
			{
				return this._filiereId;
			}
			set
			{
				if ((this._filiereId != value))
				{
					this.OnfiliereIdChanging(value);
					this.SendPropertyChanging();
					this._filiereId = value;
					this.SendPropertyChanged("filiereId");
					this.OnfiliereIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom", DbType="VarChar(200)")]
		public string Nom
		{
			get
			{
				return this._Nom;
			}
			set
			{
				if ((this._Nom != value))
				{
					this.OnNomChanging(value);
					this.SendPropertyChanging();
					this._Nom = value;
					this.SendPropertyChanged("Nom");
					this.OnNomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_responsable", DbType="VarChar(200)")]
		public string responsable
		{
			get
			{
				return this._responsable;
			}
			set
			{
				if ((this._responsable != value))
				{
					this.OnresponsableChanging(value);
					this.SendPropertyChanging();
					this._responsable = value;
					this.SendPropertyChanged("responsable");
					this.OnresponsableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filiere_etudiant", Storage="_etudiants", ThisKey="filiereId", OtherKey="FiliereId")]
		public EntitySet<etudiant> etudiants
		{
			get
			{
				return this._etudiants;
			}
			set
			{
				this._etudiants.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="filiere_etudiant1", Storage="_etudiants1", ThisKey="filiereId", OtherKey="FiliereId")]
		public EntitySet<etudiant> etudiants1
		{
			get
			{
				return this._etudiants1;
			}
			set
			{
				this._etudiants1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_etudiants(etudiant entity)
		{
			this.SendPropertyChanging();
			entity.filiere = this;
		}
		
		private void detach_etudiants(etudiant entity)
		{
			this.SendPropertyChanging();
			entity.filiere = null;
		}
		
		private void attach_etudiants1(etudiant entity)
		{
			this.SendPropertyChanging();
			entity.filiere1 = this;
		}
		
		private void detach_etudiants1(etudiant entity)
		{
			this.SendPropertyChanging();
			entity.filiere1 = null;
		}
	}
}
#pragma warning restore 1591
